name: Regenerate profile content
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'catalogs/**'

jobs:
  update:
    name: Regenerate content
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Regenerate profiles
        id: regenerate
        uses: jpower432/trestle-bot@feat/add-gh-prs
        with:
          markdown_path: "markdown/profiles"
          oscal_model: "profile"
          file_pattern: "markdown/*"
          branch: "autoupdate-${{ github.run_id }}"
          skip_assemble: true
          skip_items: "fedramp_rev5_high"
          github_token: ${{ secrets.GITHUB_TOKEN }}
